name: 'Release ready'
description: 'Check PR and add specified tag if PR is OK'
inputs:
    github_token:
        description: A GitHub token.
        required: true
    label:
        description: The label name to be added if PR can be released (or removed if not).
        required: true
    leaddev_team_id:
        description: The team ID of Github lead devs.
        required: true
    required_checks:
        description: List of required checks to test.
        required: false
runs:
    using: 'node12'
    main: 'index.js'